---
- hosts: all
  tasks:
    - name: Stop the Node.js app
      command: pm2 stop mod13_ansible_assignment
      ignore_errors: yes

    - name: Delete PM2 process
      command: pm2 delete mod13_ansible_assignment
      ignore_errors: yes

    - name: Remove the application directory
      file:
        path: /home/vboxuser/mod13_ansible_assignment
        state: absent

    - name: Stop PostgreSQL service
      service:
        name: postgresql
        state: stopped
        enabled: no

    - name: Uninstall PostgreSQL
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: absent
        purge: yes
